Dataport/terminfinder-frontend

- src/app/create-suggested-dates/create-suggested-dates.component.html
- src/app/create-suggested-dates/create-suggested-dates.component.ts
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/en-EN.json
- src/locales/platt.json
Changes to CreateSuggestedDatesComponent:
- add placeholder
- use form constants on initialization
- rename localization key for invalid end date
> fix(dab-326): start date placeholder not shown

- src/app/create-appointment/create-appointment.component.html
- src/app/create-suggested-dates/create-suggested-dates.component.html
- src/app/home/home.component.html
- src/app/links/links.component.html
- src/app/password/password.component.html
- src/app/poll/mobile-poll-table.component.html
- src/app/poll/poll.component.html
- src/app/settings/settings.component.html
- src/app/shared/components/appointment-summary/appointment-summary.component.html
- src/app/shared/components/poll-options/poll-options.component.html
- src/app/shared/components/stepper/stepper.component.html
- src/app/shared/components/suggested-date/suggested-date.component.html
> fix(215): replace bootstrap class 'no-gutters' with 'g-0'

- src/app/admin-dashboard/admin-dashboard.component.html
- src/app/create-appointment/create-appointment.component.html
- src/app/create-suggested-dates/create-suggested-dates.component.html
- src/app/home/home.component.html
- src/app/juristic/bom/bom.component.html
- src/app/links/links.component.html
- src/app/overview/overview.component.html
- src/app/password/password.component.html
- src/app/poll/mobile-poll-table.component.html
- src/app/poll/poll.component.html
- src/app/shared/components/appointment-summary/appointment-summary.component.html
- src/app/shared/components/dates-overview/dates-overview.component.html
- src/app/shared/components/navigation/navigation.component.html
- src/app/shared/components/poll-options/poll-options.component.html
- src/app/shared/components/stepper/stepper.component.html
- src/app/shared/components/suggested-date/suggested-date.component.html
> refactor(217): migrate to control flow syntax

- src/app/shared/components/checkbox-field/checkbox-field.component.scss
- src/app/shared/components/checkbox-field/checkbox-field.component.ts
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/en-EN.json
> feat: add hint for users where the password is needed

- src/app/create-suggested-dates/create-suggested-dates.component.ts
- src/app/shared/constants/validatorConstants.ts
- src/app/shared/utils/moment-utils.ts
- added all variations of the standard date format `DD.MM.YYYY` as acceptable input
- input still gets casted to expected date format
- fix typo
- apply editor suggestion to shorten import
> feat: allow variations on the date input

- src/app/juristic/privacy/privacy.component.scss
Adds styling to a dynamically loaded imprint
> feat: style privacy table

- src/app/admin-dashboard/admin-dashboard.component.html
- src/app/app.component.html
- src/app/create-appointment/create-appointment.component.html
- src/app/create-suggested-dates/create-suggested-dates.component.html
- src/app/home/home.component.html
- src/app/links/links.component.html
- src/app/overview/overview.component.html
- src/app/password/password.component.html
- src/app/plain-language/plain-language.component.ts
- src/app/poll/poll.component.html
- src/app/settings/settings.component.html
- src/app/shared/components/ad-icons/ad-icons.component.html
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/en-EN.json
- src/styles.scss
- use `h1` for content instead of title
- `h2` -> `h1`
- `h3` -> `h2`
- update font-sizes to mimic previous look
- refactor header tags from components to normal text content where sufficient
- update text for successful poll creation
fixes #309
fixes #308 
fixes #306
> fix: update header usage

- src/app/poll/poll.component.html
- src/app/shared/components/admin-info/admin-info.component.html
- src/app/shared/components/message-box/message-box.component.html
- set `role` for alerts
fixes #307
> fix: alerts not being detected by screenreaders

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/links/links.component.html
- src/app/links/links.component.ts
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/en-EN.json
- src/locales/platt.json
- src/sbom.json
- src/styles.scss
- import toastr
- generate sbom
> feat: add toast to confirm that a link got copied

- src/app/create-appointment/create-appointment.component.html
- src/app/create-suggested-dates/create-suggested-dates.component.html
- src/app/home/home.component.html
- src/app/password/password.component.html
- src/app/poll/mobile-poll-table.component.html
- src/app/poll/poll.component.html
- src/app/settings/settings.component.html
- src/app/settings/settings.component.ts
- src/app/shared/components/tos/tos.component.html
- add more error messages for password repeat
- set aria-live to assertive
> fix: screenreader issues

- backend-mock/server.js
This adds a generator with multiple suggested dates & a configurable amount of participants with random votings on the dates.
The suggested dates include every possible date & time variant, always moved a month ahead of the current time.
> feat: generate an appointment with every possible date & time variant

- src/app/create-appointment/create-appointment.component.html
- src/app/create-suggested-dates/create-suggested-dates.component.html
- src/app/create-suggested-dates/create-suggested-dates.component.scss
- src/app/home/home.component.html
- src/app/password/password.component.html
- src/app/poll/mobile-poll-table.component.html
- src/app/poll/poll.component.html
- src/app/settings/settings.component.html
- src/app/shared/components/tos/tos.component.html
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/platt.json
- add index on date enter to header & delete button
- update translation to work better with an appended index
- move delete button behind header
- replace `aria-live` because of repeated outputs with role="alert" and disabled aria-atomic
> fix: improve enter date form & replace `aria-live` with role="alert"

- src/app/admin-dashboard/admin-dashboard.component.html
- src/app/app.component.html
- src/app/create-appointment/create-appointment.component.html
- src/app/create-suggested-dates/create-suggested-dates.component.html
- src/app/home/home.component.html
- src/app/links/links.component.html
- src/app/password/password.component.html
- src/app/plain-language/plain-language.component.ts
- src/app/poll/mobile-poll-table.component.html
- src/app/poll/poll.component.html
- src/app/settings/settings.component.html
- src/app/shared/components/ad-icons/ad-icons.component.html
- src/app/shared/components/appointment-summary/appointment-summary.component.html
- src/app/shared/components/footer/footer.component.html
- src/app/shared/components/poll-options/poll-options.component.html
- src/app/sign-language/sign-language.component.ts
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/en-EN.json
- src/locales/platt.json
- aria-hidden
- empty alt text which affirms screenreaders to ignore this img
- use the same format for every `<img>`
- formatting
- add description for number of accepted participants
> refactor: images which are decorative elements

- cypress/e2e/create-dates-view.cy.ts
- cypress/e2e/settings-view.cy.ts
- src/app/create-appointment/create-appointment.component.html
- src/app/create-suggested-dates/create-suggested-dates.component.html
- src/app/home/home.component.html
- src/app/overview/overview.component.html
- src/app/poll/poll.component.html
- src/app/settings/settings.component.html
- src/app/shared/components/stepper/stepper.component.html
- move stepper under `<h1>`
- make stepper a landmark labeled by the corresponding heading
- update heading ids
- label each `<form>` | this results in them being recognized as landmarks
- update `data-id`s to better fit content
> refactor: stepper position & landmarks

- .env/.build.env
- .env/.docker.env
- src/app/admin-dashboard/admin-dashboard.component.ts
- src/app/app.module.ts
- src/app/create-appointment/create-appointment.component.ts
- src/app/create-suggested-dates/create-suggested-dates.component.ts
- src/app/juristic/accessibility/accessibility.component.ts
- src/app/juristic/bom/bom.component.ts
- src/app/juristic/imprint/imprint.component.ts
- src/app/juristic/privacy/privacy.component.ts
- src/app/juristic/terms-of-service/terms-of-service.component.ts
- src/app/links/links.component.ts
- src/app/overview/overview.component.ts
- src/app/password/password.component.ts
- src/app/plain-language/plain-language.component.ts
- src/app/poll/poll.component.ts
- src/app/settings/settings.component.ts
- src/app/shared/services/route-title.service.ts
- src/app/sign-language/sign-language.component.ts
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/en-EN.json
- src/locales/platt.json
- add service to set title
- formatting
- add/update translation where needed
> feat: include current route in title

- src/styles.scss
Size was smaller than text (1rem to 1.25rem).
> fix: h3 too small font size

- src/app/poll/poll-form-helper.service.ts
- src/app/poll/poll.component.html
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/en-EN.json
- src/locales/platt.json
- src/styles.scss
- display the total additionally when editing, previously it always showed '00'
- removed margin as it misaligned the number with the button text
> fix: add screenreader label describing total nuber of accepted dates

- cypress/e2e/poll-view.cy.ts
- src/app/poll/poll-form-helper.service.ts
When submitting multiple changes after another, now each time the TOS needs to be accepted again.
> refactor: reset tos status on submit

- src/app/create-appointment/create-appointment.component.html
- src/app/create-suggested-dates/create-suggested-dates.component.html
- src/app/home/home.component.html
- src/app/password/password.component.html
- src/app/poll/mobile-poll-table.component.html
- src/app/poll/mobile-poll-table.component.scss
- src/app/poll/poll.component.html
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/en-EN.json
- src/locales/platt.json
- src/styles.scss
- removed placeholder when no necessary info is provided (eg. doubled the lable text)
- display label where useful
- added '...' when an empty input looked weird
- removed unused translations
- put label above input on mobile poll view
- improve spacing on mobile poll view
> refactor: placeholders

- cypress/e2e/create-dates-view.cy.ts
- src/app/create-suggested-dates/create-suggested-dates.component.html
> fix: enable feature date description

- src/app/password/password.component.html
- src/app/password/password.component.scss
- src/app/password/password.component.ts
- src/app/settings/settings.component.html
- src/app/settings/settings.component.scss
- src/app/settings/settings.component.ts
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/en-EN.json
- src/locales/platt.json
- add show/hide icon to password inputs
- add translations for aria descriptions
- move key icon into the label row to make some space
- updated spacing
- remove hidden username input
> refactor: add password show/hide icon

- src/app/shared/components/stepper/stepper.component.html
- src/app/shared/components/stepper/stepper.component.scss
- src/app/shared/services/navigation-guard/navigation-guard.service.ts
- src/locales/de-DE-du.json
- src/locales/en-EN.json
- fix copy&paste error on translations
- capitalize every first letter for english, with some exceptions where it wouldn't make sense
- fix stepper breaking on smaller display sizes
- disable confirmation to leave page when working on localhost (gets annoying fast)
> fix: small issues

- src/app/admin-dashboard/admin-dashboard.component.html
- src/app/admin-dashboard/admin-dashboard.component.ts
- src/app/create-suggested-dates/create-suggested-dates.component.html
- src/app/shared/services/locale/locale.service.ts
- src/styles.scss
- start/pause poll button is greyed out again when disabled
- fixed placeholder for date description
> fix: disabled buttons focusable

- src/app/plain-language/plain-language.component.scss
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/en-EN.json
- replace `<b>` with `<strong>`
Assistive technologies don't act on `<b>`
- remove custom heading size
- update heading margin
> refactor: plain language styling

- angular.json
- src/app/overview/overview.component.html
- src/app/overview/overview.component.ts
- src/locales/de-DE-du.json
- src/locales/de-DE-sie.json
- src/locales/en-EN.json
- src/locales/platt.json
Draft: Needs https://github.com/Dataport/terminfinder-backend/pull/11 to be released.
For error description see previous link.
- display warning to user
- remove back navigation
- change forward navigation text
- remove unused service
- add development config
> fix: repost appointment

- src/app/shared/components/mediaelement-player/mediaelement-player.component.scss
- src/app/shared/components/mediaelement-player/mediaelement-player.component.ts
- update color scheme for better contrast
- set video title to relevant aria attributes
- move focus when users clicks the overlay play button to play/pause button in the controlbar
> fix: video player accessibility

- backend-mock/server.js
- cypress/e2e/admin-view.cy.ts
- cypress/fixtures/values.json
- src/app/create-suggested-dates/create-suggested-dates.component.html
- src/app/create-suggested-dates/create-suggested-dates.component.ts
- src/app/create-suggested-dates/suggested-dates-form-constants.ts
- src/app/poll/poll-form-helper.service.spec.ts
- src/app/poll/poll.component.html
- src/app/shared/models/api-data-v1-dto/suggestedDate.ts
- src/app/shared/models/suggestedDate.ts
- src/app/shared/services/transformer/model-transformer.service.ts
- enable editing of `suggestedDate` when no participant voted
- centered trash icon (again)
> feat: edit dates when no participants

- .github/workflows/node.js.yml
- Dockerfile
- package-lock.json
- package.json
- Update node to v22.18
- remove unused dev dependency `typemoq`
> feat: update packages

- package-lock.json
- package.json
I didn't find any usages of the package.
> refactor: remove unused dependency
